name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Adjust to your project's Python version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev libzbar-dev \
                             python3-setuptools python3-pip build-essential \
                             git zip zlib1g-dev autoconf automake \
                             libtool pkg-config liblcms2-dev \
                             libgmp3-dev libmpc-dev libmpfr-dev \
                             libtiff5-dev libfreetype6-dev libffi6 \
                             libffi-dev python3-venv
          pip install --upgrade Cython virtualenv
          pip install buildozer

      # Remove or skip this section if you already have a buildozer.spec file
      - name: Initialize Buildozer
        run: buildozer init
        shell: bash

      - name: Build the APK
        run: |
          buildozer -v android debug  # Change to 'release' for release APK
        shell: bash

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin
