name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev libzbar-dev \
                             python3-setuptools python3-pip build-essential \
                             git zip zlib1g-dev autoconf automake \
                             libtool pkg-config liblcms2-dev \
                             libgmp3-dev libmpc-dev libmpfr-dev \
                             libtiff5-dev libfreetype6-dev \
                             python3-venv wget unzip
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip Cython
          pip install buildozer

      - name: Install Android SDK
        run: |
          
          sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          sudo unzip -q commandlinetools-linux-8512546_latest.zip -d /usr/lib/android-sdk/cmdline-tools
          sudo mv /usr/lib/android-sdk/cmdline-tools/cmdline-tools /usr/lib/android-sdk/cmdline-tools/latest

          
          echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/lib/android-sdk/cmdline-tools/latest/bin:/usr/lib/android-sdk/platform-tools" >> $GITHUB_ENV

      - name: Accept Android SDK Licenses
        run: |
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          yes | sdkmanager --licenses

      - name: Install Required SDK Components
        run: |
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools

          
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;30.0.3" "cmdline-tools;latest"

        
          if [ ! -d "$ANDROID_SDK_ROOT/build-tools/30.0.3" ]; then
            echo "Build tools not found. Installation failed."
            exit 1
          fi

      - name: Build the APK
        run: |
          source venv/bin/activate
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          buildozer -v android debug  # Use 'release' for a release APK
        shell: bash

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin
