name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev libzbar-dev \
                             python3-setuptools python3-pip build-essential \
                             git zip zlib1g-dev autoconf automake \
                             libtool pkg-config liblcms2-dev \
                             libgmp3-dev libmpc-dev libmpfr-dev \
                             libtiff5-dev libfreetype6-dev \
                             python3-venv wget unzip
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip Cython
          pip install buildozer

      - name: Install Android SDK
        run: |
        
          sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
          
          # Download and set up command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          sudo unzip -q commandlinetools-linux-8512546_latest.zip -d /usr/lib/android-sdk/cmdline-tools
          sudo mv /usr/lib/android-sdk/cmdline-tools/cmdline-tools /usr/lib/android-sdk/cmdline-tools/latest
          
          # Set environment variables for Android SDK
          echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/lib/android-sdk/cmdline-tools/latest/bin:/usr/lib/android-sdk/platform-tools" >> $GITHUB_ENV

          Ensure the environment variables are loaded for this step
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools
