name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev libzbar-dev \
                             python3-setuptools python3-pip build-essential \
                             git zip zlib1g-dev autoconf automake \
                             libtool pkg-config liblcms2-dev \
                             libgmp3-dev libmpc-dev libmpfr-dev \
                             libtiff5-dev libfreetype6-dev \
                             python3-venv wget unzip
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip Cython
          pip install buildozer

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip -q commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV

      - name: Accept Licenses
        run: |
          mkdir -p $HOME/android-sdk/licenses
          echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/android-sdk/licenses/android-sdk-license
          echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> $HOME/android-sdk/licenses/android-sdk-license
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" >> $HOME/android-sdk/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > $HOME/android-sdk/licenses/android-sdk-preview-license

      - name: Install Required SDK Components
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          yes | sdkmanager --licenses
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

        
          sdkmanager --uninstall "build-tools;35.0.0"
          rm -rf $ANDROID_SDK_ROOT/build-tools/35.0.0

      - name: Build the APK
        run: |
          source venv/bin/activate
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          
        
          sed -i 's/android.api = .*/android.api = 30/' buildozer.spec
          sed -i 's/android.minapi = .*/android.minapi = 21/' buildozer.spec
          sed -i 's/android.sdk = .*/android.sdk = 30.0.3/' buildozer.spec
          
          buildozer -v android debug
        shell: bash

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin
