name: Build APK

on:
  push:
    branches:
      - main  # Adjust if needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Adjust as needed

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev libzbar-dev \
                             python3-setuptools python3-pip build-essential \
                             git zip zlib1g-dev autoconf automake \
                             libtool pkg-config liblcms2-dev \
                             libgmp3-dev libmpc-dev libmpfr-dev \
                             libtiff5-dev libfreetype6-dev \
                             python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip Cython
          pip install buildozer

      - name: Build the APK
        run: |
          source venv/bin/activate
          buildozer -v android debug  # Change to 'release' if needed
        shell: bash

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin
